config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'dashboard/index'
  resources :books
  resources :themes
  resources :authors
  resources :employers
  resources :students
  resources :welcome

  root to: 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:proper_name, :registration, :course, :cpf)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 ms-2">
    <%= form.label :Nome_do_Aluno, style: "display: block" %>
    <%= form.text_field :proper_name %>
  </div>

  <div class="mb-3 ms-2">
    <%= form.label :Matrícula, style: "display: block" %>
    <%= form.text_field :registration %>
  </div>

  <div class="mb-3 ms-2">
    <%= form.label :Curso, style: "display: block" %>
    <%= form.text_field :course %>
  </div>

  <div class="mb-3 ms-2">
    <%= form.label :CPF, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div class="mb-3 ms-2">
    <%= submit_tag "Enviar", class: "submit-button btn btn-success" %>
  </div>

<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Nome Próprio:</strong>
    <%= student.proper_name %>
  </p>

  <p>
    <strong>Matrícula:</strong>
    <%= student.registration %>
  </p>

  <p>
    <strong>Curso:</strong>
    <%= student.course %>
  </p>

  <p>
    <strong>CPF:</strong>
    <%= student.cpf %>
  </p>

</div>

app/views/students/edit.html.erb
<div class="p-2">
  <h1>Editando Aluno</h1>
</div>

  <%= render "form", student: @student %>

<br>

<div class="mb-3 ms-2">
  <%= link_to "Detalhes", @student, :class => "btn btn-primary p-2" %>
  <%= link_to "Voltar", students_path, :class => "btn btn-primary p-2" %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-8">
      <h1 class="h2 mt-4 mb-4">Alunos</h1>
      <div class="input-group mb-5 align-items-center">
        <span class="h5 ps-4">Período da Pesquisa: </span><label class="ms-2" for="inicio">De: </label>
        <input id="data-inicio" class="form-control ms-2" type="date" /><label class="ms-2" for="final">Até: </label>
        <input id="data-final" class="form-control ms-2" type="date" />
      </div>
    </div>
  </div>
</div>

<div class="container d-flex justify-content-end p-3">
  <%= link_to "Novo Aluno", new_student_path, :class => "btn btn-primary" %>
</div>

<div class="container">
  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>Nome</th>
        <th>Matrícula</th>
        <th>Curso</th>
        <th>CPF</th>
        <th>Editar</th>
        <th>Deletar</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.proper_name %></td>
          <td><%= student.registration %></td>
          <td><%= student.course %></td>
          <td><%= student.cpf %></td>
          <td><%= link_to "Editar", edit_student_path(student), :class => "btn btn-primary" %></td>
          <td><%= link_to "Deletar", student, method: :delete, data: {confirm: ("Tem certeza que deseja apagar ?")}, :class => "btn btn-primary" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/students/new.html.erb
<h1>Novo Aluno</h1>

<%= render "form", student: @student %>

<br>

<div class="ms-2">
  <%= link_to "Voltar para Alunos", students_path, :class => "btn btn-primary"%>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="ms-2">
  <%= render @student %>
</div>

<div class="p-3">
  <div class="p-3">
    <%= link_to "Voltar", students_path, :class => "btn btn-primary" %>
    <%= link_to "Editar", edit_student_path(@student), :class => "btn btn-primary" %>
  </div>
  <%= button_to "Apagar Estudante", @student, method: :delete, :class => "btn btn-danger" %>
</div>