config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'dashboard/index'
  resources :books
  resources :themes
  resources :authors
  resources :employers
  resources :students
  resources :welcome

  root to: 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :add_theme_to_books
  has_many :books, through: :add_theme_to_books

  attr_accessor :book

  def add_book(book)
    self.book = book
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: %i[ show edit update destroy ]

  # GET /themes or /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1 or /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes or /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to theme_url(@theme), notice: "Theme was successfully created." }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1 or /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to theme_url(@theme), notice: "Theme was successfully updated." }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1 or /themes/1.json
  def destroy
    @theme.destroy

    respond_to do |format|
      format.html { redirect_to themes_url, notice: "Theme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theme_params
      params.require(:theme).permit(:theme)
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<%= form_with(model: theme) do |form| %>
  <% if theme.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
        <% theme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 ms-2">
    <%= form.label :Nome_do_Tema, style: "display: block" %>
    <%= form.text_field :theme %>
  </div>

  <div class="mb-3 ms-2">
    <%= submit_tag "Enviar", class: "submit-button btn btn-success" %>
  </div>
<% end %>

app/views/themes/_theme.html.erb
<div id="<%= dom_id theme %>">
  <p>
    <strong>Theme:</strong>
    <%= theme.theme %>
  </p>

</div>

app/views/themes/edit.html.erb
<div class="p-2">
  <h1>Editando Tema</h1>
</div>

<%= render "form", theme: @theme %>

<br>

<div class="mb-3 ms-2">
  <%= link_to "Detalhes", @theme, :class => "btn btn-primary p-2"%>
  <%= link_to "Voltar", themes_path, :class => "btn btn-primary p-2" %>
</div>

app/views/themes/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-8">
      <h1 class="h2 mt-4 mb-4">Temas</h1>
      <div class="input-group mb-5 align-items-center">
        <span class="h5 ps-4">Período da Pesquisa: </span><label class="ms-2" for="inicio">De: </label>
        <input id="data-inicio" class="form-control ms-2" type="date" /><label class="ms-2" for="final">Até: </label>
        <input id="data-final" class="form-control ms-2" type="date" />
      </div>
    </div>
  </div>
</div>
<div class="container d-flex justify-content-end p-3">
  <%= link_to "Novo Tema", new_theme_path , :class => "btn btn-primary"%>
</div>

<div class="container">
  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>Tema</th>
        <th>Editar</th>
        <th>Deletar</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @themes.each do |theme| %>
        <tr>
          <td><%= theme.theme %></td>
          <td><%= link_to "Editar", edit_theme_path(theme), :class => "btn btn-primary" %></td>
          <td><%= link_to "Deletar", theme, method: :delete, data: {confirm: ("Tem certeza que deseja apagar ?")}, :class => "btn btn-primary" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/themes/new.html.erb
<h1>Novo Tema</h1>

<%= render "form", theme: @theme %>

<br>

<div class="ms-2">
  <%= link_to "Voltar para Temas", themes_path , :class => "btn btn-primary"%>
</div>

app/views/themes/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="ms-2">
  <%= render @theme %>
</div>

<div class="p-3">
  <div class="p-3">
  <%= link_to "Editar", edit_theme_path(@theme), :class => "btn btn-primary" %>
  <%= link_to "Voltar", themes_path, :class => "btn btn-primary" %>
  </div>
  <%= button_to "Apagar Tema", @theme, method: :delete, :class => "btn btn-danger" %>
</div>