config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'dashboard/index'
  resources :books
  resources :themes
  resources :authors
  resources :employers
  resources :students
  resources :welcome

  root to: 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/employer.rb
class Employer < ApplicationRecord
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_employer, only: %i[ show edit update destroy ]

  # GET /employers or /employers.json
  def index
    @employers = Employer.all
  end

  # GET /employers/1 or /employers/1.json
  def show
  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers or /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        format.html { redirect_to employer_url(@employer), notice: "Employer was successfully created." }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1 or /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to employer_url(@employer), notice: "Employer was successfully updated." }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1 or /employers/1.json
  def destroy
    @employer.destroy

    respond_to do |format|
      format.html { redirect_to employers_url, notice: "Employer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employer_params
      params.require(:employer).permit(:proper_name, :function, :effectuation_date, :resignation_date, :loan)
    end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_employer.html.erb
<!--As Informações e renderizações de cada funcionário estão sendo feitas-->
<!--diretamente em "employers/index.html.erb"-->

app/views/employers/_form.html.erb
<%= form_with(model: employer) do |form| %>
  <% if employer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
        <% employer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 ms-2">
    <%= form.label :Nome, style: "display: block" %>
    <%= form.text_field :proper_name %>
  </div>

  <div class="mb-3 ms-2">
    <%= form.label :Cargo, style: "display: block" %>
    <%= form.text_field :function %>
  </div>

  <div class="mb-3 ms-2">
    <%= form.label :Data_de_adimissão, style: "display: block" %>
    <%= form.date_field :effectuation_date %>
  </div>

  <div class="mb-3 ms-2">
    <%= form.label :Data_de_demissão, style: "display: block" %>
    <%= form.text_field :resignation_date %>
  </div>

  <div class="mb-3 ms-2">
    <%= form.label :Empréstimos, style: "display: block" %>
    <%= form.text_field :loans %>
  </div>

  <div class="mb-3 ms-2">
    <%= submit_tag "Enviar", class: "submit-button btn btn-success" %>
  </div>
<% end %>

app/views/employers/edit.html.erb
<div class="p-2">
  <h1>Editando Livro</h1>
</div>

<%= render "form", employer: @employer %>

<br>

<div class="mb-3 ms-2">
  <%= link_to "Detalhes", @employer, :class => "btn btn-primary p-2" %>
  <%= link_to "Voltar", employers_path, :class => "btn btn-primary p-2" %>
</div>

app/views/employers/index.html.erb
<p style="color: green"><%= notice %></p>


<div class="container">
  <div class="row">
    <div class="col-8">
      <h1 class="h2 mt-4 mb-4">Funcionários</h1>
      <div class="input-group mb-5 align-items-center">
        <span class="h5 ps-4">Período da Pesquisa: </span><label class="ms-2" for="inicio">De: </label>
        <input id="data-inicio" class="form-control ms-2" type="date" /><label class="ms-2" for="final">Até: </label>
        <input id="data-final" class="form-control ms-2" type="date" />
      </div>
    </div>
  </div>
</div>




<div class="container d-flex justify-content-end p-3">
  <%= link_to "Novo Funcionário", new_employer_path, :class => "btn btn-primary" %>
</div>

<div class="container">
  <div class="table-responsive">
    <table class="table">
      <thead>
          <tr>
            <th>Nome</th>
            <th>Cargo</th>
            <th>Data de Adimissão</th>
            <th>Data de Demissão</th>
            <th>Qtd. Empréstimos</th>
            <th>Editar</th>
            <th>Deletar</th>
            <th colspan="3"></th>
          </tr>
      </thead>

      <tbody>
        <% @employers.each do |employer| %>
            <tr>
              <td><%= employer.proper_name %></td>
              <td><%= employer.function %></td>
              <td><%= employer.effectuation_date %></td>
              <td><%= employer.resignation_date %></td>
              <td><%= employer.date %></td>
              <td><%= link_to "Editar", edit_employer_path(employer), :class => "btn btn-primary" %></td>
              <td><%= link_to "Deletar", employer, method: :delete, data: {confirm: ("Tem certeza que deseja apagar ?")}, :class => "btn btn-primary" %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/employers/new.html.erb
<h1>Novo Funcionário</h1>

<%= render "form", employer: @employer %>

<br>

<div class="ms-2">
  <%= link_to "Voltar para Funcionários", employers_path , :class => "btn btn-primary"%>
</div>

app/views/employers/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="ms-2">
  <%= render @employer %>
</div>

<div class="p-3">
  <div class="p-3">
    <%= link_to "Detalhes", edit_employer_path(@employer), :class => "btn btn-primary" %>
  <%= link_to "Voltar", employers_path, :class => "btn btn-primary" %>
  </div>
  <%= button_to "Apagar Funcionário", @employer, method: :delete, :class => "btn btn-danger" %>
</div>