config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'dashboard/index'
  resources :books
  resources :themes
  resources :authors
  resources :employers
  resources :students
  resources :welcome

  root to: 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/add_author_to_book.rb
class AddAuthorToBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/add_theme_to_book.rb
class AddThemeToBook < ApplicationRecord
  belongs_to :theme
  belongs_to :book
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :add_author_to_books
  has_many :books, through: :add_author_to_books

  attr_accessor :book

  def add_book(book)
    self.book = book
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :add_author_to_books
  has_many :authors, through: :add_author_to_books

  has_many :add_theme_to_books
  has_many :themes, through: :add_theme_to_books

  attr_accessor :author_signature

  attr_accessor :theme

  def add_author(author)
    author.book = self
  end

  def add_theme(theme)
    theme.book = self
  end

end

app/models/employer.rb
class Employer < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :add_theme_to_books
  has_many :books, through: :add_theme_to_books

  attr_accessor :book

  def add_book(book)
    self.book = book
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:proper_name, :signature)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    theme = Theme.find_by(theme: book_params[:theme])
    author = Author.find_by(signature: book_params[:author_signature])
    @book = Book.new(book_params)
    @book.theme_ids = theme.id
    @book.author_id = author.id


    respond_to do |format|
      if author and theme
        if @book.save
          AddAuthorToBook.new(author_id: author.id, book_id: @book.id)
          AddThemeToBook.new(theme_id: theme.id, book_id: @book.id)

          format.html { redirect_to book_url(@book), notice: "Livro criado com Suceso!" }
          format.json { render :show, status: :created, location: @book }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end

      else
        redirect_to new_book_path, alert: "Autor não encontrado."
      end

      # else
      #   redirect_to new_book_path, alert: "Tema não encontrado."
      # end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Livro apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:book_name, :author_id, :year, :isbn, :quantity, :author_signature, :theme_id, :theme)
  end
  end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: %i[ show edit update destroy ]

  # GET /themes or /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1 or /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes or /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to theme_url(@theme), notice: "Theme was successfully created." }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1 or /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to theme_url(@theme), notice: "Theme was successfully updated." }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1 or /themes/1.json
  def destroy
    @theme.destroy

    respond_to do |format|
      format.html { redirect_to themes_url, notice: "Theme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theme_params
      params.require(:theme).permit(:theme)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoBiblioteca</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<!--    <link rel="stylesheet" href=application.style.css>-->

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script type="application/javascript" src="<%= javascript_path "autocompleteBS" %>"></script>
  </head>

  <body>
  <div class="bg-primary text-white" class="collapse show" id="menu-collapse">
    <div class="mb-1 container">
      <nav class="d-flex flex-wrap align-items-center justify-content-lg-start">
        <button class="me-2 btn btn-toggle d-inline-flex align-items-center rounded border" aria-expanded="true" id="btn-menu">
          <svg xmlns="http://www.w3.org/2000/svg" widtd="16" height="16" fill="currentColor" class="bi bi-caret-up-fill" viewBox="0 0 16 16">
            <path d="m7.247 4.86-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0 0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z"/>
          </svg>
        </button>

        <div>
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li class="btn-menu"><%= link_to "Início", welcome_index_path,  :class => "nav-link px-2 text-white" %></li>
            <li><%= link_to "Dashboard", dashboard_index_path,  :class => "nav-link px-2 text-white" %></a></li>
            <li><%= link_to "Funcionários", employers_path ,  :class => "nav-link px-2 text-white"%></li>
            <li><%= link_to "Alunos", students_path,  :class => "nav-link px-2 text-white" %></li>
            <li><%= link_to "Livros", books_path,  :class => "nav-link px-2 text-white" %></li>
            <li><%= link_to "Autores", authors_path,  :class => "nav-link px-2 text-white" %></li>
            <li><%= link_to "Temas", themes_path ,  :class => "nav-link px-2 text-white"%></li>
            <li><%= link_to "Empréstimos", "#",  :class => "nav-link px-2 text-white" %></li>
          </ul>
        </div>
      </nav>
    </div>
  </div>

  <div class="ms-4" id="menu-oculto" >
    <div class="collapse show" >
      <button class=" ms-2 mt-2 mb-3 btn btn-toggle d-inline-flex d-none align-items-center rounded border" aria-expanded="true" id="btn-oculto">
        <svg xmlns="http://www.w3.org/2000/svg" widtd="16" height="16" fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
          <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
        </svg>
      </button>
    </div>
  </div>

<!--  <p class="notice"><%#= notice %></p>-->
<!--  <p class="alert"><%#= alert %></p>-->

  <%= yield %>
  </body>
</html>